language: php
php:
- 5.3
- 5.3.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
    - php: hhvm

env:
  global:
  ##- secure:

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --dev
  ## PHPDocumentor
  - mkdir -p build/docs
  - mkdir -p build/coverage

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs src/ --standard=PSR2 -n
  ## PHP Copy/Paste Detector
  - ./vendor/bin/phpcpd src/
  ## PHP Mess Detector
  - ./vendor/bin/phpmd src/ text ./phpmd.xml.dist
  ## PHPUnit
  ## - ./vendor/bin/phpunit -c ./ --coverage-text --coverage-html ./build/coverage
  ## PHPLOC
  - ./vendor/bin/phploc src/
  ## PHPDocumentor
  ## - ./vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"

after_script:
  ## PHPDocumentor
  ## - bash .travis_shell_after_success.sh
  ## Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  ## - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
